
INSERT [dbo].[Pavilions] ( [Surface], [Name]) VALUES ( 100, N'Africarium')
INSERT [dbo].[Pavilions] ( [Surface], [Name]) VALUES ( 50, N'Nocturnals')
INSERT [dbo].[Pavilions] ( [Surface], [Name]) VALUES ( 73, N'Apery')
INSERT [dbo].[Pavilions] ( [Surface], [Name]) VALUES ( 23, N'Aviary')
INSERT [dbo].[Pavilions] ( [Surface], [Name]) VALUES ( 205, N'Elephant house')
INSERT [dbo].[Pavilions] ( [Surface], [Name]) VALUES ( 67, N'Aquarium')

INSERT [dbo].[AnimalGroups] ( [PavilionId], [Name]) VALUES ( 3, N'Capuchin monkey')
INSERT [dbo].[AnimalGroups] ( [PavilionId], [Name]) VALUES ( 3, N'Baboons')
INSERT [dbo].[AnimalGroups] ( [PavilionId], [Name]) VALUES ( 4, N'Toucans')
INSERT [dbo].[AnimalGroups] ( [PavilionId], [Name]) VALUES ( 4, N'Parrots')
INSERT [dbo].[AnimalGroups] ( [PavilionId], [Name]) VALUES ( 6, N'Whales')
INSERT [dbo].[AnimalGroups] ( [PavilionId], [Name]) VALUES ( 6, N'Penguins')
INSERT [dbo].[AnimalGroups] ( [PavilionId], [Name]) VALUES ( 5, N'Elephants')
INSERT [dbo].[AnimalGroups] ( [PavilionId], [Name]) VALUES ( 2, N'Bats')
INSERT [dbo].[AnimalGroups] ( [PavilionId], [Name]) VALUES ( 1, N'Cats')
INSERT [dbo].[AnimalGroups] ( [PavilionId], [Name]) VALUES ( 1, N'Zebras')

INSERT [dbo].[Animals] ( [AnimalGroupId], [Name], [Species], [BirthDate], [DeathDate], [Sex]) VALUES ( 2, N'Mila', N'Hamadryas baboon', CAST(N'2018-11-12' AS Date), NULL, N'm')
INSERT [dbo].[Animals] ( [AnimalGroupId], [Name], [Species], [BirthDate], [DeathDate], [Sex]) VALUES ( 8, N'Filipus', N'Common vampire bat', CAST(N'2018-11-12' AS Date), NULL, N'm')
INSERT [dbo].[Animals] ( [AnimalGroupId], [Name], [Species], [BirthDate], [DeathDate], [Sex]) VALUES ( 7, N'Adas', N'African bush elephant', CAST(N'2018-11-12' AS Date), NULL, N'm')
INSERT [dbo].[Animals] ( [AnimalGroupId], [Name], [Species], [BirthDate], [DeathDate], [Sex]) VALUES ( 5, N'Eus', N'North Pacific right whale', CAST(N'2018-11-12' AS Date), NULL, N'k')
INSERT [dbo].[Animals] ( [AnimalGroupId], [Name], [Species], [BirthDate], [DeathDate], [Sex]) VALUES ( 10, N'Mania', N'Plains zebra', CAST(N'2018-11-12' AS Date), NULL, N'k')
INSERT [dbo].[Animals] ( [AnimalGroupId], [Name], [Species], [BirthDate], [DeathDate], [Sex]) VALUES ( 6, N'Kowalski', N'Galapagos penguin', CAST(N'2018-11-12' AS Date), NULL, N'm')
INSERT [dbo].[Animals] ( [AnimalGroupId], [Name], [Species], [BirthDate], [DeathDate], [Sex]) VALUES ( 3, N'Stasia', N'Toco toucan', CAST(N'2018-11-12' AS Date), NULL, N'm')
INSERT [dbo].[Animals] ( [AnimalGroupId], [Name], [Species], [BirthDate], [DeathDate], [Sex]) VALUES ( 7, N'Stachu', N'African bush elephant', CAST(N'2018-11-12' AS Date), NULL, N'm')
INSERT [dbo].[Animals] ( [AnimalGroupId], [Name], [Species], [BirthDate], [DeathDate], [Sex]) VALUES ( 9, N'Ecia', N'Iberian lynx', CAST(N'2018-11-12' AS Date), NULL, N'k')
INSERT [dbo].[Animals] ( [AnimalGroupId], [Name], [Species], [BirthDate], [DeathDate], [Sex]) VALUES ( 4, N'Wulf', N'Kakapo', CAST(N'2018-11-12' AS Date), NULL, N'k')
INSERT [dbo].[Animals] ( [AnimalGroupId], [Name], [Species], [BirthDate], [DeathDate], [Sex]) VALUES ( 1, N'Szymus', N'White-fronted capuchin', CAST(N'2018-11-12' AS Date), NULL, N'm')
INSERT [dbo].[Animals] ( [AnimalGroupId], [Name], [Species], [BirthDate], [DeathDate], [Sex]) VALUES ( 1, N'Zbyszek', N'White-fronted capuchin', CAST(N'2018-11-12' AS Date), NULL, N'm')

INSERT [dbo].[Employees] ( [FirstName], [LastName], [Salary], [Position], [login], [password]) VALUES ( N'Filip', N'Matuszczak', 10000, N'CEO', N'fili_69', N'asdf')
INSERT [dbo].[Employees] ( [FirstName], [LastName], [Salary], [Position], [login], [password]) VALUES ( N'Ewa', N'Dziembowska', 5000, N'Secretary', N'ewapotranspiracja', N'fdsa')
INSERT [dbo].[Employees] ( [FirstName], [LastName], [Salary], [Position], [login], [password]) VALUES ( N'Adam', N'Klejda', 5001, N'Main cleanman', N'adamklej', N'abcdef')
INSERT [dbo].[Employees] ( [FirstName], [LastName], [Salary], [Position], [login], [password]) VALUES ( N'Bartosz', N'Mila', 0, N'Slave', N'barmila', N'zxcv')
INSERT [dbo].[Employees] ( [FirstName], [LastName], [Salary], [Position], [login], [password]) VALUES ( N'Stanislaw', N'Wasik', 3000, N'Worker', N'stanwas', N'bvcn')
INSERT [dbo].[Employees] ( [FirstName], [LastName], [Salary], [Position], [login], [password]) VALUES ( N'Stanislaw', N'Gileznosa', 2999, N'Worker', N'gileznosa', N'fdhsd')

INSERT [dbo].[FoodProducts] ( [Name], [Quantity], [ExpiryDate], [Calories]) VALUES ( N'Hay', 1000, CAST(N'2018-11-12' AS Date), 1000)
INSERT [dbo].[FoodProducts] ( [Name], [Quantity], [ExpiryDate], [Calories]) VALUES ( N'Worms', 10000, CAST(N'2018-11-12' AS Date), 500)
INSERT [dbo].[FoodProducts] ( [Name], [Quantity], [ExpiryDate], [Calories]) VALUES ( N'Bananas', 50000, CAST(N'2018-11-12' AS Date), 100)
INSERT [dbo].[FoodProducts] ( [Name], [Quantity], [ExpiryDate], [Calories]) VALUES ( N'Fish food', 10000, CAST(N'2018-11-12' AS Date), 250)
INSERT [dbo].[FoodProducts] ( [Name], [Quantity], [ExpiryDate], [Calories]) VALUES ( N'Seeds', 23000, CAST(N'2018-11-12' AS Date), 140)
INSERT [dbo].[FoodProducts] ( [Name], [Quantity], [ExpiryDate], [Calories]) VALUES ( N'Plankton', 102130, CAST(N'2018-11-12' AS Date), 1)
INSERT [dbo].[FoodProducts] ( [Name], [Quantity], [ExpiryDate], [Calories]) VALUES ( N'Dead fishes', 10000, CAST(N'2018-11-12' AS Date), 500)
INSERT [dbo].[FoodProducts] ( [Name], [Quantity], [ExpiryDate], [Calories]) VALUES ( N'Blood', 80000, CAST(N'2018-11-12' AS Date), 300)

INSERT [dbo].[Feedings] ( [AnimalGroupId], [EmployeeId], [FoodProductsId], [TimeForFeeding], [FeedingDate], [Quantity]) VALUES ( 5, 4, 6, 50, CAST(N'2018-11-28' AS Date), 10)
INSERT [dbo].[Feedings] ( [AnimalGroupId], [EmployeeId], [FoodProductsId], [TimeForFeeding], [FeedingDate], [Quantity]) VALUES ( 6, 5, 7, 12, CAST(N'2018-11-28' AS Date), 10)
INSERT [dbo].[Feedings] ( [AnimalGroupId], [EmployeeId], [FoodProductsId], [TimeForFeeding], [FeedingDate], [Quantity]) VALUES ( 10, 6, 1, 32, CAST(N'2018-11-28' AS Date), 10)
INSERT [dbo].[Feedings] ( [AnimalGroupId], [EmployeeId], [FoodProductsId], [TimeForFeeding], [FeedingDate], [Quantity]) VALUES ( 8, 5, 8, 5, CAST(N'2018-11-28' AS Date), 10)
INSERT [dbo].[Feedings] ( [AnimalGroupId], [EmployeeId], [FoodProductsId], [TimeForFeeding], [FeedingDate], [Quantity]) VALUES ( 6, 4, 4, 50, CAST(N'2019-01-10' AS Date), 15)
INSERT [dbo].[Feedings] ( [AnimalGroupId], [EmployeeId], [FoodProductsId], [TimeForFeeding], [FeedingDate], [Quantity]) VALUES ( 10, 4, 1, 50, CAST(N'2019-01-12' AS Date), 10)
INSERT [dbo].[Feedings] ( [AnimalGroupId], [EmployeeId], [FoodProductsId], [TimeForFeeding], [FeedingDate], [Quantity]) VALUES ( 5, 4, 6, 50, CAST(N'2019-01-15' AS Date), 45)
INSERT [dbo].[Feedings] ( [AnimalGroupId], [EmployeeId], [FoodProductsId], [TimeForFeeding], [FeedingDate], [Quantity]) VALUES ( 6, 5, 4, 50, CAST(N'2019-01-03' AS Date), 151)
INSERT [dbo].[Feedings] ( [AnimalGroupId], [EmployeeId], [FoodProductsId], [TimeForFeeding], [FeedingDate], [Quantity]) VALUES ( 10, 5, 1, 50, CAST(N'2019-01-11' AS Date), 20)
INSERT [dbo].[Feedings] ( [AnimalGroupId], [EmployeeId], [FoodProductsId], [TimeForFeeding], [FeedingDate], [Quantity]) VALUES ( 5, 5, 6, 50, CAST(N'2019-01-17' AS Date), 2)
INSERT [dbo].[Feedings] ( [AnimalGroupId], [EmployeeId], [FoodProductsId], [TimeForFeeding], [FeedingDate], [Quantity]) VALUES ( 2, 5, 3, 50, CAST(N'2019-01-09' AS Date), 34)
INSERT [dbo].[Feedings] ( [AnimalGroupId], [EmployeeId], [FoodProductsId], [TimeForFeeding], [FeedingDate], [Quantity]) VALUES ( 6, 6, 4, 50, CAST(N'2018-12-24' AS Date), 11)
INSERT [dbo].[Feedings] ( [AnimalGroupId], [EmployeeId], [FoodProductsId], [TimeForFeeding], [FeedingDate], [Quantity]) VALUES ( 10, 6, 1, 50, CAST(N'2018-12-27' AS Date), 32)
INSERT [dbo].[Feedings] ( [AnimalGroupId], [EmployeeId], [FoodProductsId], [TimeForFeeding], [FeedingDate], [Quantity]) VALUES ( 5, 6, 6, 50, CAST(N'2019-01-01' AS Date), 34)
INSERT [dbo].[Feedings] ( [AnimalGroupId], [EmployeeId], [FoodProductsId], [TimeForFeeding], [FeedingDate], [Quantity]) VALUES ( 2, 6, 3, 50, CAST(N'2019-01-02' AS Date), 11)
INSERT [dbo].[Feedings] ( [AnimalGroupId], [EmployeeId], [FoodProductsId], [TimeForFeeding], [FeedingDate], [Quantity]) VALUES ( 6, 3, 4, 50, CAST(N'2019-01-04' AS Date), 89)
INSERT [dbo].[Feedings] ( [AnimalGroupId], [EmployeeId], [FoodProductsId], [TimeForFeeding], [FeedingDate], [Quantity]) VALUES ( 10, 3, 1, 50, CAST(N'2019-01-06' AS Date), 8)
INSERT [dbo].[Feedings] ( [AnimalGroupId], [EmployeeId], [FoodProductsId], [TimeForFeeding], [FeedingDate], [Quantity]) VALUES ( 5, 3, 6, 50, CAST(N'2019-01-16' AS Date), 9)
INSERT [dbo].[Feedings] ( [AnimalGroupId], [EmployeeId], [FoodProductsId], [TimeForFeeding], [FeedingDate], [Quantity]) VALUES ( 2, 2, 3, 50, CAST(N'2019-01-13' AS Date), 13)
INSERT [dbo].[Feedings] ( [AnimalGroupId], [EmployeeId], [FoodProductsId], [TimeForFeeding], [FeedingDate], [Quantity]) VALUES ( 4, 3, 5, 50, CAST(N'2019-01-19' AS Date), 12)
INSERT [dbo].[Feedings] ( [AnimalGroupId], [EmployeeId], [FoodProductsId], [TimeForFeeding], [FeedingDate], [Quantity]) VALUES ( 3, 2, 5, 50, CAST(N'2019-01-15' AS Date), 10)
INSERT [dbo].[Feedings] ( [AnimalGroupId], [EmployeeId], [FoodProductsId], [TimeForFeeding], [FeedingDate], [Quantity]) VALUES ( 2, 1, 3, 50, CAST(N'2019-01-20' AS Date), 12)
INSERT [dbo].[Feedings] ( [AnimalGroupId], [EmployeeId], [FoodProductsId], [TimeForFeeding], [FeedingDate], [Quantity]) VALUES ( 4, 1, 5, 50, CAST(N'2018-11-10' AS Date), 10)
INSERT [dbo].[Feedings] ( [AnimalGroupId], [EmployeeId], [FoodProductsId], [TimeForFeeding], [FeedingDate], [Quantity]) VALUES ( 3, 1, 5, 50, CAST(N'2018-12-01' AS Date), 15)

INSERT [dbo].[Cleanings] ( [EmployeeId], [PavilionId], [CleaningDate], [TimeForCleaning]) VALUES ( 1, 5, CAST(N'2018-11-28' AS Date), 1000)
INSERT [dbo].[Cleanings] ( [EmployeeId], [PavilionId], [CleaningDate], [TimeForCleaning]) VALUES ( 3, 3, CAST(N'2018-11-28' AS Date), 602)
INSERT [dbo].[Cleanings] ( [EmployeeId], [PavilionId], [CleaningDate], [TimeForCleaning]) VALUES ( 1, 2, CAST(N'2018-11-28' AS Date), 59)
INSERT [dbo].[Cleanings] ( [EmployeeId], [PavilionId], [CleaningDate], [TimeForCleaning]) VALUES ( 4, 1, CAST(N'2018-11-28' AS Date), 59)
INSERT [dbo].[Cleanings] ( [EmployeeId], [PavilionId], [CleaningDate], [TimeForCleaning]) VALUES ( 1, 1, CAST(N'2018-11-27' AS Date), 1000)
INSERT [dbo].[Cleanings] ( [EmployeeId], [PavilionId], [CleaningDate], [TimeForCleaning]) VALUES ( 2, 2, CAST(N'2018-11-29' AS Date), 100)
INSERT [dbo].[Cleanings] ( [EmployeeId], [PavilionId], [CleaningDate], [TimeForCleaning]) VALUES ( 3, 3, CAST(N'2018-11-26' AS Date), 106)
INSERT [dbo].[Cleanings] ( [EmployeeId], [PavilionId], [CleaningDate], [TimeForCleaning]) VALUES ( 4, 4, CAST(N'2018-12-30' AS Date), 102)
INSERT [dbo].[Cleanings] ( [EmployeeId], [PavilionId], [CleaningDate], [TimeForCleaning]) VALUES ( 5, 5, CAST(N'2018-12-01' AS Date), 100)
INSERT [dbo].[Cleanings] ( [EmployeeId], [PavilionId], [CleaningDate], [TimeForCleaning]) VALUES ( 6, 6, CAST(N'2018-12-02' AS Date), 200)
INSERT [dbo].[Cleanings] ( [EmployeeId], [PavilionId], [CleaningDate], [TimeForCleaning]) VALUES ( 6, 1, CAST(N'2018-12-10' AS Date), 400)
INSERT [dbo].[Cleanings] ( [EmployeeId], [PavilionId], [CleaningDate], [TimeForCleaning]) VALUES ( 6, 2, CAST(N'2018-12-12' AS Date), 10)
INSERT [dbo].[Cleanings] ( [EmployeeId], [PavilionId], [CleaningDate], [TimeForCleaning]) VALUES ( 3, 3, CAST(N'2018-12-17' AS Date), 50)
INSERT [dbo].[Cleanings] ( [EmployeeId], [PavilionId], [CleaningDate], [TimeForCleaning]) VALUES ( 3, 4, CAST(N'2019-01-05' AS Date), 70)
INSERT [dbo].[Cleanings] ( [EmployeeId], [PavilionId], [CleaningDate], [TimeForCleaning]) VALUES ( 3, 5, CAST(N'2019-01-20' AS Date), 99)
INSERT [dbo].[Cleanings] ( [EmployeeId], [PavilionId], [CleaningDate], [TimeForCleaning]) VALUES ( 4, 6, CAST(N'2019-01-12' AS Date), 12)
INSERT [dbo].[Cleanings] ( [EmployeeId], [PavilionId], [CleaningDate], [TimeForCleaning]) VALUES ( 4, 1, CAST(N'2019-01-11' AS Date), 2)
INSERT [dbo].[Cleanings] ( [EmployeeId], [PavilionId], [CleaningDate], [TimeForCleaning]) VALUES ( 4, 2, CAST(N'2019-01-06' AS Date), 23)
INSERT [dbo].[Cleanings] ( [EmployeeId], [PavilionId], [CleaningDate], [TimeForCleaning]) VALUES ( 2, 3, CAST(N'2019-01-07' AS Date), 554)
INSERT [dbo].[Cleanings] ( [EmployeeId], [PavilionId], [CleaningDate], [TimeForCleaning]) VALUES ( 2, 4, CAST(N'2019-01-02' AS Date), 53)
INSERT [dbo].[Cleanings] ( [EmployeeId], [PavilionId], [CleaningDate], [TimeForCleaning]) VALUES ( 3, 5, CAST(N'2019-01-08' AS Date), 121)
INSERT [dbo].[Cleanings] ( [EmployeeId], [PavilionId], [CleaningDate], [TimeForCleaning]) VALUES ( 3, 6, CAST(N'2019-01-03' AS Date), 18)

INSERT [dbo].[Suppliers] ( [CompanyName], [ContactName], [Address], [City], [Country], [Phone]) VALUES ( N'Foodex', N'Filip', N'Simple 12', N'Los Angeles', N'USA', N'+48-123-123-123')
INSERT [dbo].[Suppliers] ( [CompanyName], [ContactName], [Address], [City], [Country], [Phone]) VALUES ( N'Airpress Polska Sp. z o.o.', N'Ewa', N'Polanka 7', N'Poznan', N'Poland', N'+48-321-432-765')
INSERT [dbo].[Suppliers] ( [CompanyName], [ContactName], [Address], [City], [Country], [Phone]) VALUES ( N'Schiessl', N'Adam', N'Wuerfungel 182', N'Berlin', N'Germany', N'+48-654-234-987')
INSERT [dbo].[Suppliers] ( [CompanyName], [ContactName], [Address], [City], [Country], [Phone]) VALUES ( N'INTECCO', N'Mila', N'Long 712', N'New York', N'USA', N'+48-624-294-387')
INSERT [dbo].[Suppliers] ( [CompanyName], [ContactName], [Address], [City], [Country], [Phone]) VALUES ( N'Foodesy International', N'Szymon', N'Kawaii 13', N'Tokio', N'Japan', N'+48-684-194-388')

INSERT [dbo].[Delivery] ( [SupplierId], [FoodProductsId], [DeliveryDate], [Quantity]) VALUES ( 2, 2, CAST(N'2018-11-12' AS Date), 300)
INSERT [dbo].[Delivery] ( [SupplierId], [FoodProductsId], [DeliveryDate], [Quantity]) VALUES ( 1, 1, CAST(N'2018-11-12' AS Date), 300)
INSERT [dbo].[Delivery] ( [SupplierId], [FoodProductsId], [DeliveryDate], [Quantity]) VALUES ( 4, 4, CAST(N'2018-11-12' AS Date), 100)
INSERT [dbo].[Delivery] ( [SupplierId], [FoodProductsId], [DeliveryDate], [Quantity]) VALUES ( 3, 3, CAST(N'2018-11-12' AS Date), 1000)
INSERT [dbo].[Delivery] ( [SupplierId], [FoodProductsId], [DeliveryDate], [Quantity]) VALUES ( 5, 5, CAST(N'2018-11-12' AS Date), 1000)
INSERT [dbo].[Delivery] ( [SupplierId], [FoodProductsId], [DeliveryDate], [Quantity]) VALUES ( 5, 5, CAST(N'2018-11-12' AS Date), 1000)
INSERT [dbo].[Delivery] ( [SupplierId], [FoodProductsId], [DeliveryDate], [Quantity]) VALUES ( 5, 5, CAST(N'2018-11-12' AS Date), 5000)
INSERT [dbo].[Delivery] ( [SupplierId], [FoodProductsId], [DeliveryDate], [Quantity]) VALUES ( 1, 3, CAST(N'2018-11-12' AS Date), 5000)
INSERT [dbo].[Delivery] ( [SupplierId], [FoodProductsId], [DeliveryDate], [Quantity]) VALUES ( 5, 2, CAST(N'2018-11-12' AS Date), 5000)
INSERT [dbo].[Delivery] ( [SupplierId], [FoodProductsId], [DeliveryDate], [Quantity]) VALUES ( 1, 6, CAST(N'2018-12-01' AS Date), 2130)
INSERT [dbo].[Delivery] ( [SupplierId], [FoodProductsId], [DeliveryDate], [Quantity]) VALUES ( 2, 1, CAST(N'2018-12-10' AS Date), 3000)
INSERT [dbo].[Delivery] ( [SupplierId], [FoodProductsId], [DeliveryDate], [Quantity]) VALUES ( 1, 2, CAST(N'2018-12-22' AS Date), 5000)
INSERT [dbo].[Delivery] ( [SupplierId], [FoodProductsId], [DeliveryDate], [Quantity]) VALUES ( 3, 3, CAST(N'2018-12-30' AS Date), 200)
INSERT [dbo].[Delivery] ( [SupplierId], [FoodProductsId], [DeliveryDate], [Quantity]) VALUES ( 1, 4, CAST(N'2019-01-03' AS Date), 1000)
INSERT [dbo].[Delivery] ( [SupplierId], [FoodProductsId], [DeliveryDate], [Quantity]) VALUES ( 2, 5, CAST(N'2019-01-10' AS Date), 3320)
INSERT [dbo].[Delivery] ( [SupplierId], [FoodProductsId], [DeliveryDate], [Quantity]) VALUES ( 4, 6, CAST(N'2019-01-12' AS Date), 670)
INSERT [dbo].[Delivery] ( [SupplierId], [FoodProductsId], [DeliveryDate], [Quantity]) VALUES ( 5, 7, CAST(N'2019-01-18' AS Date), 1080)
INSERT [dbo].[Delivery] ( [SupplierId], [FoodProductsId], [DeliveryDate], [Quantity]) VALUES ( 4, 8, CAST(N'2019-01-15' AS Date), 2310)

