//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZOO.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class AnimalGroups
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AnimalGroups()
        {
            this.Animals = new HashSet<Animals>();
            this.Feedings = new HashSet<Feedings>();
        }
    
        public int AnimalGroupId { get; set; }
        public int PavilionId { get; set; }
        [Required(ErrorMessage ="The name is required")]
        [MinLength(3,ErrorMessage ="Minimal length of the name is 3 characters")]
        [MaxLength(20, ErrorMessage ="Maximum length of the name is 20 characters")]
        public string Name { get; set; }
        public int RowVersion { get; set; }
    
        public virtual Pavilions Pavilions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Animals> Animals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Feedings> Feedings { get; set; }
    }
}
