//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZOO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Delivery
    {
        public int DeliveryId { get; set; }
        public int SupplierId { get; set; }
        public int FoodProductsId { get; set; }
        public System.DateTime DeliveryDate { get; set; }
        public int Quantity { get; set; }
        public int RowVersion { get; set; }
    
        public virtual FoodProducts FoodProducts { get; set; }
        public virtual Suppliers Suppliers { get; set; }
    }
}
