//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZOO.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class FoodProducts
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FoodProducts()
        {
            this.Delivery = new HashSet<Delivery>();
            this.Feedings = new HashSet<Feedings>();
        }
    
        public int FoodProductsId { get; set; }
        [Required(ErrorMessage = "The name is required")]
        [MinLength(3, ErrorMessage = "Minimal length of the name is 3 characters")]
        [MaxLength(20, ErrorMessage = "Maximum length of the name is 20 characters")]
        public string Name { get; set; }
        [Required(ErrorMessage = "The quantity is required")]
        public int Quantity { get; set; }
        [Required(ErrorMessage = "The expiry date is required")]
        public System.DateTime ExpiryDate { get; set; }
        [Required(ErrorMessage = "The calories are required")]
        public int Calories { get; set; }
        public int RowVersion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Delivery> Delivery { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Feedings> Feedings { get; set; }
    }
}
