//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZOO.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Suppliers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Suppliers()
        {
            this.Delivery = new HashSet<Delivery>();
        }
    
        public int SupplierId { get; set; }
        [Required(ErrorMessage = "The company name is required")]
        [MinLength(3, ErrorMessage = "Minimal length of the company name is 3 characters")]
        [MaxLength(20, ErrorMessage = "Maximum length of the company name is 20 characters")]
        public string CompanyName { get; set; }
        [Required(ErrorMessage = "The contact name is required")]
        [MinLength(3, ErrorMessage = "Minimal length of the contact name is 3 characters")]
        [MaxLength(20, ErrorMessage = "Maximum length of the contact name is 20 characters")]
        public string ContactName { get; set; }
        [Required(ErrorMessage = "The address is required")]
        [MinLength(3, ErrorMessage = "Minimal length of the address is 3 characters")]
        [MaxLength(100, ErrorMessage = "Maximum length of the address is 100 characters")]
        public string Address { get; set; }
        [Required(ErrorMessage = "The city is required")]
        [MinLength(3, ErrorMessage = "Minimal length of the city is 3 characters")]
        [MaxLength(20, ErrorMessage = "Maximum length of the city is 20 characters")]
        public string City { get; set; }
        [Required(ErrorMessage = "The country is required")]
        [MinLength(3, ErrorMessage = "Minimal length of the country is 3 characters")]
        [MaxLength(20, ErrorMessage = "Maximum length of the name is 20 characters")]
        public string Country { get; set; }
        [Required(ErrorMessage = "Phone is a Required field.")]
        [RegularExpression("\\+[0-9]{2}-[0-9]{3}-[0-9]{3}-[0-9]{3}",
                ErrorMessage = "Phone is required and must be properly formatted.")]
        [Display(Order = 9, Name = "Phone")]
        public string Phone { get; set; }
        public int RowVersion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Delivery> Delivery { get; set; }
    }
}
